# 配置Sharding-JDBC数据源名称，可配置多个
spring:
  shardingsphere:
    datasource:
      name: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: jdbc:log4jdbc:mysql://localhost:3306/dataset-annotation?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&useInformationSchema=true
        username: root
        password: 123456
      props:
        sql:
          show: true
management:
  health:
    db:
      enabled: false