server:
  # rest API 版本号
  rest-version: v1

# data模块配置
data:
  annotation:
    task:
      # 自动标注任务分割的文件split size
      splitSize: 16
      # 单位ms
      retryInterval: 5000
      # 任务不更新置为失败的时间单位秒
      failTime: 43200
  server:
    # 文件存储服务器用户名
    userName: root

# 资源回收
recycle:
  # 超时时间
  over-second:
    # 数据集文件 5小时
    file: 18000
    # 数据集版本文件 5小时
    version-file: 18000
  
# ES服务地址及端口
es:
  host: 192.168.199.187
  serverPort: 32321
  transportPort: 32311
  clusterName: kubernetes-logging
  index: dataset_text_test

# serving预测上传文件大小限制
spring:
  servlet:
    multipart:
      # 设置单个文件的大小
      max-file-size: 10MB
      # 设置单次请求的文件的总大小
      max-request-size: 100MB
  shardingsphere:
    #指定data_dataset表 主键id 生成策略
    sharding:
      tables:
        data_file:
          actual-data-nodes: master.data_file_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm

        data_dataset_version_file:
          actual-data-nodes: master.data_dataset_version_file_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm

        data_file_annotation:
          actual-data-nodes: master.data_file_annotation_$->{1..250}
          table-strategy:
            standard:
              sharding-column: dataset_id
              precise-algorithm-class-name: org.dubhe.data.util.MyPreciseShardingAlgorithm