#网关路由转发相关实例
spring:
  cloud:
    gateway:
      enabled: true
      routes:
        # id唯一表示 路由至admin服务
        - id: admin-route
          # uri=> lb://服务名称
          uri: lb://admin
          # 路由规则
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - StripPrefix=3
        # 路由至auth服务
        - id: auth-route
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=3
        # id唯一表示 路由至data(数据集)服务
        - id: dubhe-data
          # uri=> lb://服务名称
          uri: lb://dubhe-data
          # 路由规则
          predicates:
            - Path=/api/v1/data/**
          filters:
            - StripPrefix=3
